version: "3.8"

#Creamos los servicios que serian de mysql y nodejs
services:
  mysqldb:
  # La imagen es de mysql en su version 5.7
    image: mysql:5.7
   
   #Las variables de entorno se declaran en el archivo .env
    env_file: ./.env

    #Declaramos todas las variables de entorno que ya creamos en el archivo .env
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
    #El numero de puerto tambien se encuentra ya en la variable de entorno declarada anteriormente.
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    logging:
      driver: none

  app:
  # EN el servicio de la app tenemos la parte del Nodejs
    depends_on:
    #Este servicio depende del anterior, ya que cuando se termine de ejecutar el anterior, se ejecutara este contenedor.
      - mysqldb
    links:
      - mysqldb
    build: .
    # La construccion de este contenedor se creara mediante el dockerfile.
    env_file: ./.env

    #Declaramos todas las variables de entorno que ya creamos en el archivo .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    volumes:
    #Se creara un volumen en el cual se almacenaran los servicio y se ubica en la carpeta /myapp.
      - .:/myapp
    command: sh -c "npm install && npm run dev"

